# Generated by Django 5.2.7 on 2025-11-22 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الرحلة')),
                ('duration_days', models.PositiveIntegerField(verbose_name='عدد الأيام')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='السعر الإجمالي')),
                ('daily_plan', models.JSONField(default=dict, verbose_name='الخطة اليومية')),
                ('included_services', models.JSONField(default=list, verbose_name='الخدمات المشمولة')),
                ('special_requests', models.TextField(blank=True, null=True, verbose_name='طلبات خاصة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('quoted', 'مسعر'), ('confirmed', 'مؤكد'), ('booked', 'محجوز'), ('completed', 'مكتمل'), ('cancelled', 'ملغى')], default='draft', max_length=15, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_trips', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'رحلة مخصصة',
                'verbose_name_plural': 'الرحلات المخصصة',
                'db_table': 'custom_trips',
            },
        ),
        migrations.CreateModel(
            name='CustomTripDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_order', models.PositiveIntegerField(verbose_name='ترتيب الزيارة')),
                ('duration_hours', models.PositiveIntegerField(verbose_name='المدة بالساعات')),
                ('visit_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الزيارة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('custom_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.customtrip', verbose_name='الرحلة المخصصة')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.destination', verbose_name='الوجهة')),
            ],
            options={
                'verbose_name': 'وجهة الرحلة المخصصة',
                'verbose_name_plural': 'وجهات الرحلات المخصصة',
                'db_table': 'custom_trip_destinations',
                'ordering': ['visit_order'],
                'unique_together': {('custom_trip', 'destination')},
            },
        ),
        migrations.AddField(
            model_name='customtrip',
            name='destinations',
            field=models.ManyToManyField(through='bookings.CustomTripDestination', to='packages.destination', verbose_name='الوجهات'),
        ),
        migrations.CreateModel(
            name='CustomTripService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(verbose_name='رقم اليوم')),
                ('time_slot', models.CharField(choices=[('morning', 'صباح'), ('afternoon', 'بعد الظهر'), ('evening', 'مساء')], max_length=10, verbose_name='الفترة')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('date', models.DateField(blank=True, null=True, verbose_name='التاريخ')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('custom_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.customtrip', verbose_name='الرحلة المخصصة')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.service', verbose_name='الخدمة')),
            ],
            options={
                'verbose_name': 'خدمة الرحلة المخصصة',
                'verbose_name_plural': 'خدمات الرحلات المخصصة',
                'db_table': 'custom_trip_services',
                'ordering': ['day_number', 'time_slot'],
            },
        ),
        migrations.AddField(
            model_name='customtrip',
            name='services',
            field=models.ManyToManyField(through='bookings.CustomTripService', to='packages.service', verbose_name='الخدمات'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(max_length=20, unique=True, verbose_name='رقم الحجز')),
                ('booking_type', models.CharField(choices=[('package', 'باقة جاهزة'), ('custom', 'رحلة مخصصة')], max_length=10, verbose_name='نوع الحجز')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'مؤكد'), ('paid', 'مدفوع'), ('active', 'نشط'), ('completed', 'مكتمل'), ('cancelled', 'ملغى'), ('refunded', 'تم الاسترداد')], default='pending', max_length=15, verbose_name='حالة الحجز')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الإجمالي')),
                ('number_of_travelers', models.PositiveIntegerField(default=1, verbose_name='عدد المسافرين')),
                ('traveler_details', models.JSONField(default=list, verbose_name='تفاصيل المسافرين')),
                ('special_requests', models.TextField(blank=True, null=True, verbose_name='طلبات خاصة')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('booking_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحجز')),
                ('confirmation_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التأكيد')),
                ('cancellation_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإلغاء')),
                ('cancellation_reason', models.TextField(blank=True, null=True, verbose_name='سبب الإلغاء')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='packages.package', verbose_name='الباقة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('custom_trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.customtrip', verbose_name='الرحلة المخصصة')),
            ],
            options={
                'verbose_name': 'حجز',
                'verbose_name_plural': 'الحجوزات',
                'db_table': 'bookings',
                'indexes': [models.Index(fields=['user', 'status'], name='bookings_user_id_1eeb34_idx'), models.Index(fields=['booking_number'], name='bookings_booking_502bea_idx'), models.Index(fields=['start_date', 'end_date'], name='bookings_start_d_527bc3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='customtrip',
            index=models.Index(fields=['user', 'status'], name='custom_trip_user_id_554607_idx'),
        ),
        migrations.AddIndex(
            model_name='customtrip',
            index=models.Index(fields=['status', 'created_at'], name='custom_trip_status_a7f683_idx'),
        ),
    ]
