# Generated by Django 5.2.7 on 2025-11-22 11:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='معرف الجلسة')),
                ('initial_requirements', models.JSONField(default=dict, verbose_name='المتطلبات الأولية')),
                ('conversation_history', models.JSONField(default=list, verbose_name='سجل المحادثة')),
                ('extracted_preferences', models.JSONField(default=dict, verbose_name='التفضيلات المستخلصة')),
                ('generated_plan', models.JSONField(default=dict, verbose_name='الخطة المولدة')),
                ('budget_range', models.JSONField(default=dict, verbose_name='نطاق الميزانية')),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد الأيام')),
                ('status', models.CharField(choices=[('active', 'نشطة'), ('plan_generated', 'تم توليد الخطة'), ('price_quoted', 'تم التسعير'), ('completed', 'مكتملة'), ('cancelled', 'ملغاة')], default='active', max_length=20, verbose_name='حالة الجلسة')),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر التقريبي')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر النهائي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('expires_at', models.DateTimeField(verbose_name='تاريخ الانتهاء')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'جلسة محادثة',
                'verbose_name_plural': 'جلسات المحادثة',
                'db_table': 'chat_sessions',
            },
        ),
        migrations.CreateModel(
            name='AIRecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('destination', 'وجهة'), ('package', 'باقة'), ('service', 'خدمة'), ('custom_plan', 'خطة مخصصة')], max_length=20, verbose_name='نوع التوصية')),
                ('input_parameters', models.JSONField(default=dict, verbose_name='معاملات الإدخال')),
                ('output_recommendations', models.JSONField(default=list, verbose_name='التوصيات المخرجة')),
                ('confidence_score', models.FloatField(default=0.0, verbose_name='درجة الثقة')),
                ('user_feedback', models.CharField(blank=True, max_length=10, null=True, verbose_name='تقييم المستخدم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='chat.chatsession', verbose_name='جلسة المحادثة')),
            ],
            options={
                'verbose_name': 'سجل توصيات الذكاء الاصطناعي',
                'verbose_name_plural': 'سجلات توصيات الذكاء الاصطناعي',
                'db_table': 'ai_recommendation_logs',
            },
        ),
        migrations.CreateModel(
            name='TravelPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_type', models.CharField(choices=[('accommodation', 'الإقامة'), ('transportation', 'المواصلات'), ('food', 'الطعام'), ('activities', 'الأنشطة'), ('budget', 'الميزانية'), ('pace', 'سرعة الرحلة')], max_length=20, verbose_name='نوع التفضيل')),
                ('preference_key', models.CharField(max_length=100, verbose_name='مفتاح التفضيل')),
                ('preference_value', models.JSONField(default=dict, verbose_name='قيمة التفضيل')),
                ('weight', models.FloatField(default=1.0, verbose_name='الأهمية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_preferences', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تفضيل سفر',
                'verbose_name_plural': 'تفضيلات السفر',
                'db_table': 'travel_preferences',
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', 'status'], name='chat_sessio_user_id_39df70_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['expires_at'], name='chat_sessio_expires_1b562e_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['session_id'], name='chat_sessio_session_a3bcba_idx'),
        ),
        migrations.AddIndex(
            model_name='airecommendationlog',
            index=models.Index(fields=['user', 'recommendation_type'], name='ai_recommen_user_id_d78d1a_idx'),
        ),
        migrations.AddIndex(
            model_name='airecommendationlog',
            index=models.Index(fields=['session', 'created_at'], name='ai_recommen_session_115dc3_idx'),
        ),
        migrations.AddIndex(
            model_name='travelpreference',
            index=models.Index(fields=['user', 'preference_type'], name='travel_pref_user_id_d74549_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='travelpreference',
            unique_together={('user', 'preference_type', 'preference_key')},
        ),
    ]
