# Generated by Django 5.2.7 on 2025-11-22 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('type', models.CharField(choices=[('family', 'عائلية'), ('adventure', 'مغامرة'), ('cultural', 'ثقافية'), ('honeymoon', 'شهر عسل'), ('religious', 'دينية')], max_length=20, verbose_name='النوع')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('short_description', models.CharField(max_length=300, verbose_name='وصف مختصر')),
                ('duration_days', models.PositiveIntegerField(verbose_name='عدد الأيام')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الأساسي')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر الخصم')),
                ('included_services', models.JSONField(default=list, verbose_name='الخدمات المشمولة')),
                ('excluded_services', models.JSONField(default=list, verbose_name='الخدمات غير المشمولة')),
                ('daily_schedule', models.JSONField(verbose_name='الجدول اليومي')),
                ('terms_conditions', models.TextField(verbose_name='الشروط والأحكام')),
                ('cancellation_policy', models.TextField(verbose_name='سياسة الإلغاء')),
                ('image_urls', models.JSONField(default=list, verbose_name='الصور')),
                ('popularity_count', models.IntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'باقة',
                'verbose_name_plural': 'الباقات',
                'db_table': 'packages',
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('type', models.CharField(choices=[('city', 'مدينة'), ('historical', 'موقع تاريخي'), ('natural', 'موقع طبيعي'), ('coastal', 'ساحلي')], max_length=20, verbose_name='النوع')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('governorate', models.CharField(max_length=50, verbose_name='المحافظة')),
                ('latitude', models.FloatField(verbose_name='خط العرض')),
                ('longitude', models.FloatField(verbose_name='خط الطول')),
                ('popularity_score', models.IntegerField(default=0, verbose_name='مستوى الشعبية')),
                ('best_season', models.CharField(max_length=100, verbose_name='أفضل موسم')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='صورة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'وجهة',
                'verbose_name_plural': 'الوجهات',
                'db_table': 'destinations',
                'indexes': [models.Index(fields=['governorate', 'type'], name='destination_governo_9e08d3_idx'), models.Index(fields=['popularity_score'], name='destination_popular_04b6f0_idx')],
            },
        ),
        migrations.CreateModel(
            name='PackageDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_order', models.PositiveIntegerField(verbose_name='ترتيب الزيارة')),
                ('duration_hours', models.PositiveIntegerField(verbose_name='المدة بالساعات')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.destination', verbose_name='الوجهة')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.package', verbose_name='الباقة')),
            ],
            options={
                'verbose_name': 'وجهة الباقة',
                'verbose_name_plural': 'وجهات الباقات',
                'db_table': 'package_destinations',
                'ordering': ['visit_order'],
                'unique_together': {('package', 'destination')},
            },
        ),
        migrations.AddField(
            model_name='package',
            name='destinations',
            field=models.ManyToManyField(through='packages.PackageDestination', to='packages.destination', verbose_name='الوجهات'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('type', models.CharField(choices=[('hotel', 'فندق'), ('transport', 'مواصلات'), ('restaurant', 'مطعم'), ('activity', 'نشاط ترفيهي'), ('guide', 'مرشد سياحي')], max_length=20, verbose_name='النوع')),
                ('level', models.CharField(choices=[('economy', 'اقتصادي'), ('standard', 'قياسي'), ('premium', 'متميز'), ('luxury', 'فاخر')], default='standard', max_length=15, verbose_name='المستوى')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم الهاتف')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('unit_description', models.CharField(max_length=100, verbose_name='وصف الوحدة')),
                ('capacity', models.IntegerField(blank=True, null=True, verbose_name='السعة')),
                ('features', models.JSONField(default=list, verbose_name='المميزات')),
                ('rating', models.FloatField(default=0.0, verbose_name='التقييم')),
                ('image_urls', models.JSONField(default=list, verbose_name='الصور')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='packages.destination', verbose_name='الوجهة')),
            ],
            options={
                'verbose_name': 'خدمة',
                'verbose_name_plural': 'الخدمات',
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='PackageService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(verbose_name='رقم اليوم')),
                ('time_slot', models.CharField(choices=[('morning', 'صباح'), ('afternoon', 'بعد الظهر'), ('evening', 'مساء')], max_length=10, verbose_name='الفترة')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.package', verbose_name='الباقة')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.service', verbose_name='الخدمة')),
            ],
            options={
                'verbose_name': 'خدمة الباقة',
                'verbose_name_plural': 'خدمات الباقات',
                'db_table': 'package_services',
                'ordering': ['day_number', 'time_slot'],
            },
        ),
        migrations.AddField(
            model_name='package',
            name='services',
            field=models.ManyToManyField(through='packages.PackageService', to='packages.service', verbose_name='الخدمات'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['type', 'level'], name='services_type_9dfc07_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['destination', 'type'], name='services_destina_ecf5b5_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['type', 'is_active'], name='packages_type_e704ee_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['base_price'], name='packages_base_pr_fb1021_idx'),
        ),
    ]
