# Generated by Django 5.2.7 on 2025-11-22 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(max_length=20, unique=True, verbose_name='رقم الدفع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('payment_method', models.CharField(choices=[('credit_card', 'بطاقة ائتمان'), ('debit_card', 'بطاقة خصم'), ('bank_transfer', 'تحويل بنكي'), ('digital_wallet', 'محفظة إلكترونية')], max_length=20, verbose_name='طريقة الدفع')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('processing', 'قيد المعالجة'), ('completed', 'مكتمل'), ('failed', 'فاشل'), ('refunded', 'تم الاسترداد'), ('cancelled', 'ملغى')], default='pending', max_length=15, verbose_name='حالة الدفع')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='معرف المعاملة')),
                ('payment_gateway_response', models.JSONField(blank=True, null=True, verbose_name='رد بوابة الدفع')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مبلغ الاسترداد')),
                ('refund_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاسترداد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking', verbose_name='الحجز')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'الدفعات',
                'db_table': 'payments',
                'indexes': [models.Index(fields=['payment_number'], name='payments_payment_c27a96_idx'), models.Index(fields=['booking', 'status'], name='payments_booking_52233d_idx')],
            },
        ),
    ]
