# Generated by Django 5.2.7 on 2025-11-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('gateway_type', models.CharField(max_length=50, verbose_name='النوع')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('credentials', models.JSONField(default=dict, verbose_name='بيانات الاعتماد')),
                ('test_mode', models.BooleanField(default=True, verbose_name='وضع الاختبار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'بوابة دفع',
                'verbose_name_plural': 'بوابات الدفع',
                'db_table': 'payment_gateways',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('SYP', 'ليرة سورية'), ('USD', 'دولار أمريكي'), ('EUR', 'يورو')], default='SYP', max_length=3, verbose_name='العملة'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_gateway',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='بوابة الدفع'),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_reason',
            field=models.TextField(blank=True, null=True, verbose_name='سبب الاسترداد'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='payments_transac_a1f824_idx'),
        ),
    ]
